### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by kevgals** [luke-r-mills/ESP8266_ST7735_IR_CryptoTicker#1] opened 2021-11-07 15:25 UTC
Hi, forgive me if I am doing this incorrectly, very new to this. I have just built this, on power up it allowed me to enter my network credentials, seemed to work for about a minute but now has a scrolling "Coin Track" screen.

**Comment by luke-r-mills** [comment] 2021-11-07 15:45
Hi, that's a weird issue, I will add the specific components and pin configuration to the README.md later, you can check with them if the components and pins match. Otherwise, I am currently fixing some crashes that happen when the WiFi connection is weak, it might have something to do with that? If you could attach a picture/video that might help me narrow down where the problem is. Cheers

**Comment by kevgals** [comment] 2021-11-07 16:28
https://user-images.githubusercontent.com/64653996/140653370-36536ce6-628b-439f-b995-683144f1119e.mp4

**Comment by kevgals** [comment] 2021-11-07 16:29
I'll check my wiring later when you post details later. Thank you for your prompt reply

**Comment by luke-r-mills** [comment] 2021-11-07 18:40
I have added the configuration and the libraries I used into the README, check if your wiring matches that (it looks like we have used the same display based on your video). If everything matches and it's still broken, make sure the libraries match, you might need to change the ESP8266 library you selected in the Board Manager in Arduino back to 2.7.4. Try and reinstall the sketch using that and that should hopefully fix the issue. In future, I will update the sketch so that it uses the latest library.

If the issue persists, then you might need to upload a new sketch to clear the EEPROM memory (basically a really small storage space on the board), then reinstall the original. Let me know if you need this and I will quickly make that and add it to the repo! Let me know if any of the above works, it's a weird bug that I have never encountered before!

**Comment by kevgals** [comment] 2021-11-07 21:19
Put the ESP8266 library back to 2.7.4 in boards manager and everything (apart from time) seems good)

**Comment by luke-r-mills** [comment] 2021-11-07 21:23
Glad to hear its working! I have opened a separate issue for the time, so will close this now. Cheers

**Closed by luke-r-mills** 2021-11-07 21:23 UTC
